"""initial schema

Revision ID: ff2d81d934e3
Revises: 
Create Date: 2026-04-29 15:12:05.452166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2d81d934e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_atr_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('time_period', sa.Integer(), nullable=False),
    sa.Column('atr_value', sa.Float(), nullable=True),
    sa.Column('atr_date', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'interval', 'time_period', name='uq_atr_ticker_interval_period')
    )
    op.create_table('market_daily_bar_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('bar_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'bar_date', name='uq_daily_bar_ticker_date')
    )
    op.create_table('market_indicator_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('time_period', sa.Integer(), nullable=False),
    sa.Column('sma_value', sa.Float(), nullable=True),
    sa.Column('sma_date', sa.Date(), nullable=True),
    sa.Column('close_value', sa.Float(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'interval', 'time_period', name='uq_mic_ticker_interval_period')
    )
    op.create_table('market_weekly_bar_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('bar_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'bar_date', name='uq_weekly_bar_ticker_date')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=False),
    sa.Column('initial_purchase_date', sa.Date(), nullable=False),
    sa.Column('investment_type', sa.String(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('daily_close', sa.Float(), nullable=True),
    sa.Column('daily_sma_21', sa.Float(), nullable=True),
    sa.Column('daily_market_date', sa.Date(), nullable=True),
    sa.Column('daily_retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('weekly_close', sa.Float(), nullable=True),
    sa.Column('weekly_sma_20', sa.Float(), nullable=True),
    sa.Column('weekly_market_date', sa.Date(), nullable=True),
    sa.Column('weekly_retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_error', sa.String(), nullable=True),
    sa.Column('refresh_in_progress', sa.Boolean(), nullable=True),
    sa.Column('refresh_started_at', sa.DateTime(), nullable=True),
    sa.Column('sector_benchmark_ticker', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_rule_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investment_type', sa.String(), nullable=False),
    sa.Column('rule_key', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('params_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investment_type', 'rule_key', name='uq_strategy_rule_configs_type_key')
    )
    op.create_table('position_key_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('level_price', sa.Float(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_key_levels')
    op.drop_table('strategy_rule_configs')
    op.drop_table('positions')
    op.drop_table('market_weekly_bar_cache')
    op.drop_table('market_indicator_cache')
    op.drop_table('market_daily_bar_cache')
    op.drop_table('market_atr_cache')
    # ### end Alembic commands ###
